-- -- Insert initial data for clients
-- INSERT INTO clients (id, first_name, last_name, middle_name, age) VALUES
--                                                                       (1, 'John', 'Doe', 'A', 30),
--                                                                       (2, 'Jane', 'Smith', 'B', 25);
--
-- -- Insert initial data for pets
-- -- Note: 'Cat' and 'Dog' should match your PetType enum values.
-- INSERT INTO pets (id, name, type, age, date_of_birth, adopted) VALUES
--                                                                               (1, 'Fluffy', 'CAT', 3, '2021-05-15', FALSE),
--                                                                               (2, 'Rover', 'DOG', 2, '2022-01-22', FALSE);
